name: WaveDecompNet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - h5py
  - numpy
  - scipy==1.8.0
  - obspy
  - cartopy
  - tzdata
  - sqlite
  - jedi
  - ncurses
  - matplotlib-inline
  - pygments
  - backcall
  - wheel
  - zlib
  - pyparsing
  - llvm-openmp
  - pip
  - executing
  - ld_impl_linux-64
  - libuuid
  - backports.functools_lru_cache
  - parso
  - decorator
  - traitlets
  - entrypoints
  - pyzmq
  - libzlib
  - prompt-toolkit
  - stack_data
  - ca-certificates
  - libgcc-ng
  - bzip2
  - pure_eval
  - asttokens
  - debugpy
  - wcwidth
  - _libgcc_mutex
  - tornado
  - six
  - libnsl
  - libsodium
  - setuptools
  - xz
  - nest-asyncio
  - packaging
  - ptyprocess
  - pexpect
  - psutil
  - ipython
  - pickleshare
  - backports
  - readline
  - libffi
  - jupyter_client
  - python-dateutil
  - tk
  - python_abi
  - libstdcxx-ng
  - openssl
  - jupyter_core
  - zeromq
  - _openmp_mutex
  - ipykernel
  - pandas
  - pip:
      - joblib==1.1.0
      - scikit-learn==1.0.2
      - sklearn==0.0
      - threadpoolctl==3.1.0
      - torch==1.10.2
      - torchinfo==1.7.0
      - tqdm==4.64.0
      - typing-extensions==4.1.1
      - utm==0.7.0
